// ============================================================================
// PACKAGE DECLARATION
// ============================================================================
// NODE.JS EQUIVALENT: This is like the folder structure
//   In Node.js: src/models/course.js or src/entities/course.js
//   In NestJS:  src/course/entities/course.entity.ts
package com.example.todo.model;

// ============================================================================
// IMPORTS - Java annotations and classes
// ============================================================================
// @Schema: Swagger/OpenAPI documentation annotation
// NODE.JS EQUIVALENT: 
//   - Plain Node.js: No direct equivalent (you'd document in JSDoc comments)
//   - NestJS: @ApiProperty() from @nestjs/swagger
//   Example:
//     @ApiProperty({ description: 'Course entity' })
import io.swagger.v3.oas.annotations.media.Schema;

// @NotBlank, @Size: Validation annotations
// NODE.JS EQUIVALENT:
//   - Plain Node.js: class-validator library
//   - NestJS: Built-in with class-validator
//   Example:
//     @IsNotEmpty() @MinLength(1) @MaxLength(200)
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

// @Id: MongoDB document ID annotation
// NODE.JS EQUIVALENT:
//   - Plain Node.js: mongoose.Schema({ _id: ... }) or just let Mongoose handle it
//   - NestJS: @Prop() with @Schema() from @nestjs/mongoose
import org.springframework.data.annotation.Id;

// @Document: MongoDB collection mapping
// NODE.JS EQUIVALENT:
//   - Plain Node.js: mongoose.model('Course', courseSchema)
//   - NestJS: @Schema() decorator from @nestjs/mongoose
import org.springframework.data.mongodb.core.mapping.Document;

// LocalDateTime: Date/time handling
// NODE.JS EQUIVALENT: JavaScript Date object or libraries like moment/dayjs
//   const createdAt = new Date();
import java.time.LocalDateTime;

// ============================================================================
// CLASS DECLARATION WITH ANNOTATIONS
// ============================================================================
// @Document: Maps this class to MongoDB collection "courses"
// NODE.JS EQUIVALENT (Plain Node.js with Mongoose):
//   const courseSchema = new mongoose.Schema({
//     name: { type: String, required: true },
//     description: String,
//     createdAt: { type: Date, default: Date.now },
//     updatedAt: { type: Date, default: Date.now }
//   }, { collection: 'courses' });
//   const Course = mongoose.model('Course', courseSchema);
//
// NODE.JS EQUIVALENT (NestJS):
//   @Schema({ collection: 'courses' })
//   export class Course extends Document {
//     ...
//   }
@Document(collection = "courses")

// @Schema: Swagger documentation
// NODE.JS EQUIVALENT (NestJS):
//   @ApiProperty({ description: 'Course entity' })
@Schema(description = "Course entity")
public class Course {

    // ============================================================================
    // FIELD DECLARATIONS
    // ============================================================================
    
    // @Id: Marks this as the MongoDB document ID
    // NODE.JS EQUIVALENT (Plain Node.js with Mongoose):
    //   // Mongoose automatically creates _id field, no need to declare
    //   // But if you want to reference it:
    //   _id: mongoose.Schema.Types.ObjectId
    //
    // NODE.JS EQUIVALENT (NestJS):
    //   @Prop({ type: mongoose.Schema.Types.ObjectId })
    //   _id?: mongoose.Types.ObjectId;
    //
    //   // Or use @Prop() without type - NestJS/Mongoose handles it automatically
    @Id
    // accessMode = Schema.AccessMode.READ_ONLY means:
    //   - This field appears in API responses (GET requests)
    //   - This field is NOT shown in request body examples (POST/PUT requests)
    //   - Users should NOT send this field when creating/updating
    //   - It's automatically generated by the server (like auto-increment IDs)
    //
    // WHY READ_ONLY?
    //   - The ID is generated by MongoDB when you save the document
    //   - Users shouldn't (and can't) provide the ID when creating a course
    //   - But the ID is returned in responses so clients can use it
    //
    // NODE.JS EQUIVALENT (NestJS Swagger):
    //   @ApiProperty({ 
    //     description: 'Unique identifier',
    //     example: '507f1f77bcf86cd799439011',
    //     readOnly: true  // <-- This is the equivalent!
    //   })
    //
    // NODE.JS EQUIVALENT (Plain Node.js):
    //   // In JSDoc comments:
    //   /**
    //    * @swagger
    //    * components:
    //    *   schemas:
    //    *     Course:
    //    *       properties:
    //    *         id:
    //    *           type: string
    //    *           description: Unique identifier
    //    *           readOnly: true  // <-- Equivalent
    //    */
    @Schema(description = "Unique identifier of the course", example = "507f1f77bcf86cd799439011", accessMode = Schema.AccessMode.READ_ONLY)
    private String id;  // NODE.JS: In Mongoose, this would be _id (automatically created)

    // @NotBlank: Field cannot be null, empty, or whitespace
    // @Size: Validates string length
    // NODE.JS EQUIVALENT (Plain Node.js with Mongoose):
    //   name: {
    //     type: String,
    //     required: [true, 'Course name is required'],
    //     minlength: [1, 'Course name must be at least 1 character'],
    //     maxlength: [200, 'Course name must not exceed 200 characters'],
    //     trim: true  // Removes whitespace
    //   }
    //
    // NODE.JS EQUIVALENT (NestJS with class-validator):
    //   @ApiProperty({ description: 'Name of the course', example: 'Spring Boot Fundamentals' })
    //   @IsNotEmpty({ message: 'Course name is required' })
    //   @Length(1, 200, { message: 'Course name must be between 1 and 200 characters' })
    //   name: string;
    @NotBlank(message = "Course name is required")
    @Size(min = 1, max = 200, message = "Course name must be between 1 and 200 characters")
    @Schema(description = "Name of the course", example = "Spring Boot Fundamentals", required = true)
    private String name;  // NODE.JS: name: string;

    // @Size: Optional field with max length validation
    // NODE.JS EQUIVALENT (Plain Node.js with Mongoose):
    //   description: {
    //     type: String,
    //     maxlength: [1000, 'Description must not exceed 1000 characters']
    //   }
    //
    // NODE.JS EQUIVALENT (NestJS):
    //   @ApiProperty({ description: 'Course description', example: 'Learn Spring Boot from scratch' })
    //   @MaxLength(1000, { message: 'Description must not exceed 1000 characters' })
    //   @IsOptional()
    //   description?: string;
    @Size(max = 1000, message = "Description must not exceed 1000 characters")
    @Schema(description = "Course description", example = "Learn Spring Boot from scratch")
    private String description;  // NODE.JS: description?: string; (optional)

    // Timestamp fields
    // READ_ONLY because:
    //   - These are automatically set by the server (not by the user)
    //   - createdAt is set when the document is first created
    //   - updatedAt is automatically updated when the document is modified
    //   - Users should NOT send these fields in POST/PUT requests
    //
    // NODE.JS EQUIVALENT (Plain Node.js with Mongoose):
    //   createdAt: {
    //     type: Date,
    //     default: Date.now
    //   }
    //
    // NODE.JS EQUIVALENT (NestJS):
    //   @ApiProperty({ 
    //     description: 'Timestamp when the course was created', 
    //     readOnly: true  // <-- Equivalent to accessMode.READ_ONLY
    //   })
    //   @Prop({ default: Date.now })
    //   createdAt?: Date;
    @Schema(description = "Timestamp when the course was created", example = "2025-11-06T12:00:00", accessMode = Schema.AccessMode.READ_ONLY)
    private LocalDateTime createdAt;  // NODE.JS: createdAt?: Date;

    @Schema(description = "Timestamp when the course was last updated", example = "2025-11-06T12:30:00", accessMode = Schema.AccessMode.READ_ONLY)
    private LocalDateTime updatedAt;  // NODE.JS: updatedAt?: Date;

    // ============================================================================
    // CONSTRUCTORS
    // ============================================================================
    // NODE.JS EQUIVALENT (Plain Node.js):
    //   // JavaScript doesn't need explicit constructors for simple objects
    //   // You can just create objects:
    //   const course = { name: 'Spring Boot', description: 'Learn Spring' };
    //
    //   // Or with a class:
    //   constructor(name, description) {
    //     this.name = name;
    //     this.description = description;
    //   }
    //
    // NODE.JS EQUIVALENT (NestJS):
    //   // TypeScript classes work similarly
    //   constructor(name?: string, description?: string) {
    //     this.name = name;
    //     this.description = description;
    //   }
    public Course() {
        // Default constructor - NODE.JS: Not needed, JavaScript objects are flexible
    }

    public Course(String name, String description) {
        this.name = name;
        this.description = description;
        // NODE.JS: constructor(name, description) { this.name = name; this.description = description; }
    }

    // ============================================================================
    // GETTERS AND SETTERS
    // ============================================================================
    // NODE.JS EQUIVALENT:
    //   // In JavaScript, you typically access properties directly:
    //   course.name = 'Spring Boot';
    //   console.log(course.name);
    //
    //   // Or use getters/setters if you need validation:
    //   get name() { return this._name; }
    //   set name(value) { 
    //     if (!value || value.trim() === '') throw new Error('Name required');
    //     this._name = value;
    //   }
    //
    //   // In TypeScript/NestJS, you can use access modifiers:
    //   // public name: string;  // Direct access (most common)
    //   // Or private with getters/setters if needed
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}




