using Microsoft.Extensions.Logging;
using MongoDB.Driver;
using UserAccountService.Infrastructure.Data;
using UserAccountService.Extensions;
using UserAccountService.Models;
using UserAccountService.Application.Services;
using UserAccountService.Infrastructure.Services;
using Shared.Constants;
using Shared.Application.Extensions;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container
builder.Services.AddControllers(options =>
{
    // Apply global validation filter - automatically validates all incoming requests
    // This mimics NestJS's ValidationPipe behavior:
    // - Validates DTOs using Data Annotations before controller actions execute
    // - Returns consistent ApiResponse format for validation errors
    // - Eliminates need for manual ModelState.IsValid checks in controllers
    options.Filters.Add<Shared.Application.Filters.ValidateModelAttribute>();
})
    .AddJsonOptions(options =>
    {
        // Allow case-insensitive property matching (camelCase from frontend -> PascalCase in C#)
        options.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
        options.JsonSerializerOptions.PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
    })
    .AddMvcOptions(options =>
    {
        // Register TransformModelBinderProvider to enable [Transform] attribute
        // This allows field transformation similar to NestJS's @Transform decorator
        options.ModelBinderProviders.Insert(0, new Shared.Application.ModelBinders.TransformModelBinderProvider());
    });
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// MongoDB Configuration using Options pattern
builder.Services.AddUserAccountMongoDb(builder.Configuration);

// Register services
builder.Services.AddUserAccountServices();

// JWT Authentication Configuration using Options pattern
builder.Services.AddJwtAuthentication(builder.Configuration);

// Register RabbitMQ Service using Options pattern
builder.Services.AddRabbitMQService(builder.Configuration);

// CORS Configuration using Options pattern
builder.Services.AddCorsPolicy(builder.Configuration, builder.Environment);

var app = builder.Build();

// Configure the HTTP request pipeline
// Global exception handler must be first
app.UseGlobalExceptionHandler();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseCors("DefaultPolicy"); // Changed from "AllowAll" to "DefaultPolicy"
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

// Ensure database indexes are created and seed admin user (with error handling)
try
{
    using (var scope = app.Services.CreateScope())
    {
        var context = scope.ServiceProvider.GetRequiredService<MongoDbContext>();
        var authService = scope.ServiceProvider.GetRequiredService<IAuthService>();
        var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
        
        logger.LogInformation("Attempting to create MongoDB indexes and seed admin user...");
        
        // Create indexes
        await context.CreateIndexesAsync();
        
        // Seed admin user if it doesn't exist
        var adminEmail = "admin@example.com";
        var filter = Builders<UserAccount>.Filter.Eq(u => u.Email, adminEmail.ToLower());
        var adminExists = await context.UserAccounts.Find(filter).AnyAsync();
        
        if (!adminExists)
        {
            var adminUser = new UserAccount
            {
                // Id will be auto-generated by MongoDB as ObjectId
                Name = "Admin User",
                Email = adminEmail.ToLower(),
                PasswordHash = authService.HashPassword("Admin@123"), // Default admin password
                Role = "admin",
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };
            await context.UserAccounts.InsertOneAsync(adminUser);
            logger.LogInformation("Admin user seeded successfully");
        }
        else
        {
            logger.LogInformation("Admin user already exists");
        }
        
        logger.LogInformation("MongoDB initialization completed successfully");
    }
}
catch (MongoException ex)
{
    var logger = app.Services.GetRequiredService<ILogger<Program>>();
    var mongoDbSettings = app.Configuration.GetSection("MongoDb").Get<Shared.Application.Options.MongoDbSettings>();
    logger.LogError(ex, "Failed to initialize MongoDB (create indexes or seed admin user). The application will continue, but some features may not work correctly. " +
                        "Please ensure MongoDB is running and accessible.");
}
catch (Exception ex)
{
    var logger = app.Services.GetRequiredService<ILogger<Program>>();
    logger.LogError(ex, "An unexpected error occurred while initializing MongoDB. The application will continue.");
}

// Start RabbitMQ listener (optional - app will still run if RabbitMQ is unavailable)
try
{
    var rabbitMQService = app.Services.GetRequiredService<Shared.Infrastructure.Services.IRabbitMQService>();
    
    rabbitMQService.StartListening(RabbitMQConstants.UserAccountServiceQueue, async (messageJson, routingKey) =>
    {
        // Create a scope for each message to resolve scoped services
        using var scope = app.Services.CreateScope();
        var messageHandler = scope.ServiceProvider.GetRequiredService<UserAccountMessageHandler>();
        var result = await messageHandler.HandleMessage(messageJson, routingKey);
        return result;
    });
    
    var logger = app.Services.GetRequiredService<ILogger<Program>>();
    logger.LogInformation("RabbitMQ listener started successfully");
}
catch (Exception ex)
{
    var logger = app.Services.GetRequiredService<ILogger<Program>>();
    logger.LogWarning(ex, "Failed to start RabbitMQ listener. The application will continue without RabbitMQ messaging. " +
                          "Please ensure RabbitMQ is running if you need messaging functionality.");
}

// Register RabbitMQService disposal on application shutdown
app.Lifetime.ApplicationStopping.Register(() =>
{
    try
    {
        var rabbitMQService = app.Services.GetRequiredService<Shared.Infrastructure.Services.IRabbitMQService>();
        if (rabbitMQService is IDisposable disposable)
        {
            disposable.Dispose();
        }
    }
    catch (Exception ex)
    {
        var logger = app.Services.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "Error disposing RabbitMQ service during shutdown");
    }
});

// Run the application
app.Run();

